# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class LabifyVillageCensusFieldsFinal(models.Model):
    state_code = models.TextField(blank=True, null=True)  # This field type is a guess.
    state = models.TextField(blank=True, null=True)  # This field type is a guess.
    dist_code = models.TextField(blank=True, null=True)  # This field type is a guess.
    dist_name = models.TextField(blank=True, null=True)  # This field type is a guess.
    sub_dist_name = models.TextField(blank=True, null=True)  # This field type is a guess.
    sub_dist_code = models.TextField(blank=True, null=True)  # This field type is a guess.
    vil_code = models.TextField(blank=True, null=True)  # This field type is a guess.
    vil_name = models.TextField(blank=True, null=True)  # This field type is a guess.
    cdb_code = models.TextField(blank=True, null=True)  # This field type is a guess.
    cdb_name = models.TextField(blank=True, null=True)  # This field type is a guess.
    gram_pan_code = models.TextField(blank=True, null=True)  # This field type is a guess.
    gram_pan_name = models.TextField(blank=True, null=True)  # This field type is a guess.
    ref_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    sub_dist_hquarter_name = models.TextField(blank=True, null=True)  # This field type is a guess.
    sub_dist_hquarter_distance = models.TextField(blank=True, null=True)  # This field type is a guess.
    dist_hquarter_name = models.TextField(blank=True, null=True)  # This field type is a guess.
    dist_hquarter_dist = models.TextField(blank=True, null=True)  # This field type is a guess.
    nearest_stat_town_name = models.TextField(blank=True, null=True)  # This field type is a guess.
    nearest_stat_town_dist = models.TextField(blank=True, null=True)  # This field type is a guess.
    within_state_ut_name = models.TextField(blank=True, null=True)  # This field type is a guess.
    within_state_ut_dist = models.TextField(blank=True, null=True)  # This field type is a guess.
    outside_state_ut_name = models.TextField(blank=True, null=True)  # This field type is a guess.
    outside_state_ut_dist = models.TextField(blank=True, null=True)  # This field type is a guess.
    tot_geograph_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    tot_households = models.TextField(blank=True, null=True)  # This field type is a guess.
    tot_population = models.TextField(blank=True, null=True)  # This field type is a guess.
    tot_male_population = models.TextField(blank=True, null=True)  # This field type is a guess.
    tot_female_population = models.TextField(blank=True, null=True)  # This field type is a guess.
    tot_sc_population = models.TextField(blank=True, null=True)  # This field type is a guess.
    tot_scm_population = models.TextField(blank=True, null=True)  # This field type is a guess.
    tot_scf_population = models.TextField(blank=True, null=True)  # This field type is a guess.
    tot_st_population = models.TextField(blank=True, null=True)  # This field type is a guess.
    tot_stm_population = models.TextField(blank=True, null=True)  # This field type is a guess.
    tot_stf_population = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_preprim_sch_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_preprim_sch_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_preprim_sch_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_preprim_sch_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_preprim = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_preprim = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_preprim = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_prim_sch_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_prim_sch_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_prim_sch_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_prim_sch_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_prim = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_prim = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_prim = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_mid_sch_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_mid_sch_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_mid_sch_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_mid_sch_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_mid = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_mid = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_mid = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_sec_sch_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_sec_sch_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_sec_sch_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_sec_sch_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_sec = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_sec = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_sec = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_sen_sec_sch_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_sen_sec_sch_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_sen_sec_sch_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_sen_sec_sch_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_sen_sec = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_sen_sec = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_sen_sec = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_deg_col_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_deg_col_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_deg_col_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_deg_col_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_deg_col = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_deg_col = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_deg_col = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_eng_col_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_eng_col_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_eng_col_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_eng_col_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_eng_col = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_eng_col = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_eng_col = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_med_col_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_med_col_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_med_col_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_med_col_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_med_col = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_med_col = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_med_col = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_mgmt_inst_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_mgmt_inst_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_mgmt_inst_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_mgmt_inst_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_mgmt_inst = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_mgmt_inst = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_mgmt_inst = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_polytech_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_polytech_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_polytech_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_polytech_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_polytech = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_polytech = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_polytech = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_voc_training_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_voc_training_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_voc_training_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_voc_training_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_voc_training = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_voc_training = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_voc_training = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_nonformal_training_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_nonformal_training_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_nonformal_training_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_nonformal_training_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_nonformal_training = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_nonformal_training = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_nonformal_training = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_sch_for_dasabled_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_sch_for_dasabled_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_sch_for_dasabled_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pvt_sch_for_dasabled_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_sch_for_dasabled = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_sch_for_dasabled = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_sch_for_dasabled = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_others_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    gov_others_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    pri_others_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    pri_others_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_status_others = models.TextField(blank=True, null=True)  # This field type is a guess.
    nfaci_village_town_others = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_others = models.TextField(blank=True, null=True)  # This field type is a guess.
    com_health_centre_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    com_health_centre_doct_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    com_health_centre_doct_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    com_health_centre_staff_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    com_health_centre_staff_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_com_health_centre = models.TextField(blank=True, null=True)  # This field type is a guess.
    prim_health_centre_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    prim_health_centre_doct_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    prim_health_centre_doct_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    prim_health_centre_staff_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    prim_health_centre_staff_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_prim_health_centre = models.TextField(blank=True, null=True)  # This field type is a guess.
    prim_health_subcent_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    prim_health_subcent_doct_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    prim_health_subcent_doct_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    prim_health_subcent_staff_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    prim_health_subcent_staff_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_prim_health_subcent = models.TextField(blank=True, null=True)  # This field type is a guess.
    mat_child_wel_centre_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    mat_child_wel_centre_doct_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    mat_child_wel_centre_doct_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    mat_child_wel_centre_staff_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    mat_child_wel_centre_staff_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_mat_child_wel_centre = models.TextField(blank=True, null=True)  # This field type is a guess.
    tb_clinic_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    tb_clinic_doct_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    tb_clinic_doct_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    tb_clinic_staff_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    tb_clinic_staff_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_tb_clinic = models.TextField(blank=True, null=True)  # This field type is a guess.
    hosp_allopath_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    hosp_allopath_doct_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    hosp_allopath_doct_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    hosp_allopath_staff_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    hosp_allopath_staff_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_hosp_allopath = models.TextField(blank=True, null=True)  # This field type is a guess.
    hosp_alt_medicine_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    hosp_alt_medicine_doct_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    hosp_alt_medicine_doct_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    hosp_alt_medicine_staff_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    hosp_alt_medicine_staff_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_hosp_alt_medicine = models.TextField(blank=True, null=True)  # This field type is a guess.
    dispensary_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    dispensary_doct_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    dispensary_doct_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    dispensary_staff_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    dispensary_staff_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_dispensary = models.TextField(blank=True, null=True)  # This field type is a guess.
    vet_hospital_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    vet_hospital_doct_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    vet_hospital_doct_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    vet_hospital_staff_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    vet_hospital_staff_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_vet_hospital = models.TextField(blank=True, null=True)  # This field type is a guess.
    mob_health_clinic_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    mob_health_clinic_doct_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    mob_health_clinic_doct_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    mob_health_clinic_staff_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    mob_health_clinic_staff_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_mob_health_clinic = models.TextField(blank=True, null=True)  # This field type is a guess.
    fam_welfare_centre_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    fam_welfare_centre_doct_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    fam_welfare_centre_doct_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    fam_welfare_centre_staff_tot_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    fam_welfare_centre_staff_inpos_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_distcode_mob_fam_welfare_centre = models.TextField(blank=True, null=True)  # This field type is a guess.
    ngvt_med_fac_out_pat_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ngvt_med_fac_in_out_pat_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ngvt_med_fac_charitable_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ngvt_med_fac_med_practitioner_mbbs_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ngvt_med_fac_med_practitioner_otherdeg_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ngvt_med_fac_med_practitioner_nodeg_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ngvt_med_fac_med_practitioner_faithhealer_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ngvt_med_fac_medicine_shop_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    ngvt_med_fac_others_nos = models.TextField(blank=True, null=True)  # This field type is a guess.
    tap_water_treated_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    tap_water_treated_fn_round_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    tap_water_treated_fn_summer_months = models.TextField(blank=True, null=True)  # This field type is a guess.
    tap_water_untreated_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    tap_water_untreated_fn_round_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    tap_water_untreated_fn_summer_months = models.TextField(blank=True, null=True)  # This field type is a guess.
    cov_well_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    cov_well_fn_round_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    cov_well_fn_summer_months = models.TextField(blank=True, null=True)  # This field type is a guess.
    uncov_well_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    uncov_well_fn_round_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    uncov_well_fn_summer_months = models.TextField(blank=True, null=True)  # This field type is a guess.
    han_pump_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    han_pump_fn_round_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    han_pump_fn_summer_months = models.TextField(blank=True, null=True)  # This field type is a guess.
    tub_wells_borehole_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    tub_wells_fn_round_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    tub_wells_fn_summer_months = models.TextField(blank=True, null=True)  # This field type is a guess.
    spring_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    spring_fn_round_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    spring_fn_summer_months = models.TextField(blank=True, null=True)  # This field type is a guess.
    river_canal_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    river_canal_fn_round_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    river_canal_fn_summer_months = models.TextField(blank=True, null=True)  # This field type is a guess.
    tank_pond_lake_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    tank_pond_lake_fn_round_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    tank_pond_lake_fn_summer_months = models.TextField(blank=True, null=True)  # This field type is a guess.
    others_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    others_fn_round_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    others_fn_summer_months = models.TextField(blank=True, null=True)  # This field type is a guess.
    closed_drainage_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    open_drainage_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    no_drainage_status = models.TextField(db_column='no _drainage_status', blank=True, null=True)  # Field renamed to remove unsuitable characters. This field type is a guess.
    op_pucca_drainage_cov_w_tiles_slabs_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    op_pucca_drainage_uncovered_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    op_kuccha_drainage_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    drainage_discharge_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    area_covered_tot_sanitation_campaign_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    com_toilet_complex_w_bath_gen_public = models.TextField(blank=True, null=True)  # This field type is a guess.
    com_toilet_complex_no_bath_gen_public = models.TextField(blank=True, null=True)  # This field type is a guess.
    rural_prod_cent_sanitary_hw_outlet_availability = models.TextField(blank=True, null=True)  # This field type is a guess.
    rural_prod_mart_sanitary_hw_outlet_availability = models.TextField(blank=True, null=True)  # This field type is a guess.
    com_waste_disposal_system = models.TextField(blank=True, null=True)  # This field type is a guess.
    com_biogas_recycle_of_waste = models.TextField(blank=True, null=True)  # This field type is a guess.
    no_system_garbage_onroads = models.TextField(blank=True, null=True)  # This field type is a guess.
    post_office_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_post_office = models.TextField(blank=True, null=True)  # This field type is a guess.
    sub_post_office_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_sub_post_office = models.TextField(blank=True, null=True)  # This field type is a guess.
    post_telegraph_office_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_post_telegraph_office = models.TextField(blank=True, null=True)  # This field type is a guess.
    vil_pin_code_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_vil_pin_code = models.TextField(blank=True, null=True)  # This field type is a guess.
    pin_code = models.TextField(blank=True, null=True)  # This field type is a guess.
    tel_landlines_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_tel_landlines = models.TextField(blank=True, null=True)  # This field type is a guess.
    pco_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_pco = models.TextField(blank=True, null=True)  # This field type is a guess.
    mob_phone_coverage_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_mob_phone_coverage = models.TextField(blank=True, null=True)  # This field type is a guess.
    internet_cafe_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_internet_cafe = models.TextField(blank=True, null=True)  # This field type is a guess.
    pri_courier_facility_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_pri_courier_facility = models.TextField(blank=True, null=True)  # This field type is a guess.
    pub_bus_service_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_pub_bus_service = models.TextField(blank=True, null=True)  # This field type is a guess.
    pri_bus_service_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_pri_bus_service = models.TextField(blank=True, null=True)  # This field type is a guess.
    railway_station_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_railway_station = models.TextField(blank=True, null=True)  # This field type is a guess.
    auto_modified_autos_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_auto_modified_autos = models.TextField(blank=True, null=True)  # This field type is a guess.
    taxi_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_taxi = models.TextField(blank=True, null=True)  # This field type is a guess.
    van_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_van = models.TextField(blank=True, null=True)  # This field type is a guess.
    tractor_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_tractor = models.TextField(blank=True, null=True)  # This field type is a guess.
    cycle_pulled_rickshaws_manual_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_cycle_pulled_rickshaws_manual = models.TextField(blank=True, null=True)  # This field type is a guess.
    cycle_pulled_rickshaws_machine_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_cycle_pulled_rickshaws_machine = models.TextField(blank=True, null=True)  # This field type is a guess.
    carts_by_animals_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_carts_by_animals = models.TextField(blank=True, null=True)  # This field type is a guess.
    sea_river_ferry_service_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_sea_river_ferry_service = models.TextField(blank=True, null=True)  # This field type is a guess.
    nat_highway_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_nat_highway = models.TextField(blank=True, null=True)  # This field type is a guess.
    state_highway_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_state_highway = models.TextField(blank=True, null=True)  # This field type is a guess.
    major_district_road_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_major_district_road = models.TextField(blank=True, null=True)  # This field type is a guess.
    oth_district_road_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_oth_district_road = models.TextField(blank=True, null=True)  # This field type is a guess.
    black_topped_pucca_road_staus = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_black_topped_pucca_road = models.TextField(blank=True, null=True)  # This field type is a guess.
    gravel_kuchha_roads_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_gravel_kuchha_roads = models.TextField(blank=True, null=True)  # This field type is a guess.
    water_bounded_macadam_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_wat_bounded_macadam = models.TextField(blank=True, null=True)  # This field type is a guess.
    all_weather_road_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_all_weather_road = models.TextField(blank=True, null=True)  # This field type is a guess.
    navigable_waterways_river_canal_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_navigable_waterways_river_canal = models.TextField(blank=True, null=True)  # This field type is a guess.
    footpath_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_footpath = models.TextField(blank=True, null=True)  # This field type is a guess.
    atm_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_atm = models.TextField(blank=True, null=True)  # This field type is a guess.
    commercial_bank_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_commercial_bank = models.TextField(blank=True, null=True)  # This field type is a guess.
    cooperative_bank_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_cooperative_bank = models.TextField(blank=True, null=True)  # This field type is a guess.
    agri_credit_societies_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_agri_credit_societies = models.TextField(blank=True, null=True)  # This field type is a guess.
    selfhelp_group_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_selfhelp_group = models.TextField(blank=True, null=True)  # This field type is a guess.
    public_distribution_system_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_public_distribution_system = models.TextField(blank=True, null=True)  # This field type is a guess.
    mandis_regular_market_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_mandis_regular_market = models.TextField(blank=True, null=True)  # This field type is a guess.
    weekly_haat_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_weekly_haat = models.TextField(blank=True, null=True)  # This field type is a guess.
    agri_marketing_society_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_agri_marketing_society = models.TextField(blank=True, null=True)  # This field type is a guess.
    nutritional_centres_icds_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_nutritional_centres_icds = models.TextField(blank=True, null=True)  # This field type is a guess.
    nutritional_centres_anganwadi_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_nutritional_centres_anganwadi = models.TextField(blank=True, null=True)  # This field type is a guess.
    nutritional_centres_others_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_nutritional_centres_others = models.TextField(blank=True, null=True)  # This field type is a guess.
    asha_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_asha = models.TextField(blank=True, null=True)  # This field type is a guess.
    community_centre_with_tv = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_community_centre_with_tv = models.TextField(blank=True, null=True)  # This field type is a guess.
    sports_field_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_sports_field = models.TextField(blank=True, null=True)  # This field type is a guess.
    sports_club_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_sports_club = models.TextField(blank=True, null=True)  # This field type is a guess.
    cinema_video_hall_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_cinema_video_hall = models.TextField(blank=True, null=True)  # This field type is a guess.
    public_library_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_public_library = models.TextField(blank=True, null=True)  # This field type is a guess.
    pub_reading_room_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_pub_reading_room = models.TextField(blank=True, null=True)  # This field type is a guess.
    daily_newspaper_supply_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_daily_newspaper_supply = models.TextField(blank=True, null=True)  # This field type is a guess.
    assembly_polling_station_status = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_assembly_polling_station = models.TextField(blank=True, null=True)  # This field type is a guess.
    birth_death_registration_office = models.TextField(blank=True, null=True)  # This field type is a guess.
    ina_dist_birth_death_registration_office = models.TextField(blank=True, null=True)  # This field type is a guess.
    power_supply_dom_use = models.TextField(blank=True, null=True)  # This field type is a guess.
    power_supply_dom_use_summer_hrspd = models.TextField(blank=True, null=True)  # This field type is a guess.
    power_supply_dom_use_winter_hrspd = models.TextField(blank=True, null=True)  # This field type is a guess.
    power_supply_agri_use = models.TextField(blank=True, null=True)  # This field type is a guess.
    power_supply_agri_use_summer_hrspd = models.TextField(blank=True, null=True)  # This field type is a guess.
    power_supply_agri_use_winter_hrspd = models.TextField(blank=True, null=True)  # This field type is a guess.
    power_supply_comm_use = models.TextField(blank=True, null=True)  # This field type is a guess.
    power_supply_comm_use_summer_hrspd = models.TextField(blank=True, null=True)  # This field type is a guess.
    power_supply_comm_use_winter_hrspd = models.TextField(blank=True, null=True)  # This field type is a guess.
    power_supply_for_all_users = models.TextField(blank=True, null=True)  # This field type is a guess.
    power_supply_for_all_users_summer_hrspd = models.TextField(blank=True, null=True)  # This field type is a guess.
    power_supply_for_all_users_winter_hrspd = models.TextField(blank=True, null=True)  # This field type is a guess.
    agri_commodities_first = models.TextField(blank=True, null=True)  # This field type is a guess.
    manufacturers_commodities_first = models.TextField(blank=True, null=True)  # This field type is a guess.
    handicrafts_commodities_first = models.TextField(blank=True, null=True)  # This field type is a guess.
    agri_commodities_second = models.TextField(blank=True, null=True)  # This field type is a guess.
    manufacturers_commodities_second = models.TextField(blank=True, null=True)  # This field type is a guess.
    handicrafts_commodities_second = models.TextField(blank=True, null=True)  # This field type is a guess.
    agri_commodities_third = models.TextField(blank=True, null=True)  # This field type is a guess.
    manufacturers_commodities_third = models.TextField(blank=True, null=True)  # This field type is a guess.
    handicrafts_commodities_third = models.TextField(blank=True, null=True)  # This field type is a guess.
    forest_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    non_agri_use_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    barren_uncoltivable_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    permanent_pastures_other_grazing_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    land_misc_tree_crops_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    culturable_wasteland_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    fallows_land_otherthan_current_fallows_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    current_fallows_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    net_area_sown = models.TextField(blank=True, null=True)  # This field type is a guess.
    tot_unirrigatedland_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    area_irrigated_by_source = models.TextField(blank=True, null=True)  # This field type is a guess.
    canals_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    wells_tube_wells_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    tanks_lakes_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    waterfall_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    other_source_area = models.TextField(blank=True, null=True)  # This field type is a guess.
    nearest_town_name = models.TextField(blank=True, null=True)  # This field type is a guess.
    dist_nearest_town = models.TextField(blank=True, null=True)  # This field type is a guess.

    class Meta:
        managed = False
        db_table = 'labify_village_census_fields_final'
